name: 'poi-update-manifest-json-action'
description: 'poi-update-manifest-json-action'
author: 'poi-vrc'
inputs:
  full-version:
    required: true
    description: 'Full version to add to/update the manifest'
    default: ''
  manifest-file-path:
    required: false
    description: 'The manifest JSON file path'
    default: 'updater_manifest.json'
  updated-at-time:
    required: false
    description: 'Updated at ISO time. Leave blank to automatically generate.'
    default: ''
  release-github-url:
    required: false
    description: 'Github URL to release. Leave blank to automatically generate.'
    default: ''
  release-booth-url:
    required: true
    description: 'Booth URL to release'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
